### ISSUE TITLE
this is complete shit

### ISSUE THREAD

**Issue by VenTaz** [Xiloe/byctify#1]
Hello,

I don't want to be mean, but please, remove this repository from your github.
First of all, it is outdated.
Second, "Simple RE" should do the the work : lol
Third, 
![image](https://user-images.githubusercontent.com/40668720/107815025-0fe0f600-6d73-11eb-8152-d41d45a04de6.png)
 : very nice offset mate 
![image](https://user-images.githubusercontent.com/40668720/107814984-0192da00-6d73-11eb-8181-0624e8a4c701.png)
Fourth, 
![image](https://user-images.githubusercontent.com/40668720/107815050-18d1c780-6d73-11eb-928e-0221103c4e96.png) AttachCurrentThread and GetEnv are hooked, so this is completely detected ; moreover, JVMTI capabilities are removed from their JVM, so 
![image](https://user-images.githubusercontent.com/40668720/107815122-39018680-6d73-11eb-97a4-c5dcc0982eea.png) "might work" no, it can't.

**Comment by Xiloe** [comment]
Thx
